server:
  port: 8086
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: chess-api
  profiles:
    active: dev

